context:
  name: powershell
  version: 7.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/PowerShell-${{ version }}-win-x64.zip
    sha256: c270f392d63d4297d78730fbffc0fefa2aa7fb39c80307c3105d22cd7fc9040e
    target_directory: powershell

build:
  number: 0
  skip:
    - not win
  script: |
    xcopy powershell "%PREFIX%\powershell" /E /I /F /B /Y
    if %ERRORLEVEL% neq 0 exit 1
    echo F | xcopy %RECIPE_DIR%\pwsh.cmd %PREFIX%\Scripts\pwsh.cmd /F /Y
    if %ERRORLEVEL% neq 0 exit 1

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compiler names include 'c', 'cxx' and 'fortran', among others.
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}  # If you need any compiler, add the C standard library ("stdlib") too
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - script:
      - where powershell
      - if not exist %PREFIX%\\powershell\\pwsh.exe exit 1

about:
  summary: PowerShell for every system!
  license: MIT
  license_file:
    - powershell/LICENSE.txt
    - powershell/ThirdPartyNotices.txt
    - powershell/assets/additionalAttributions.txt

  homepage: https://github.com/PowerShell/PowerShell

extra:
  recipe-maintainers:
    - dhirschfeld
