context:
  name: powershell
  version: 7.6.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://raw.githubusercontent.com/PowerShell/PowerShell/refs/tags/v${{ version }}/assets/additionalAttributions.txt
    sha256: cd2d609357d2eebb43ada3870b9a63eb2c155c237ca89ad6cfaa4215023a5dab
    target_directory: powershell/assets
  - if: win and x86_64
    then:
      - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/PowerShell-${{ version }}-win-x64.zip
        sha256: 32e0dd26752483ba3f0e40e9ae44150643cbff469c13210c93295d158bfd7b26
        target_directory: powershell
  - if: win and arm64
    then:
      - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/PowerShell-${{ version }}-win-arm64.zip
        sha256: 4dfc686a7aa872fe427d0508b89cef6069c01861c59d8844ae1ffb4d2d7ae017
        target_directory: powershell
  - if: linux and x86_64
    then:
      - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/powershell-${{ version }}-linux-x64.tar.gz
        sha256: 6cbcfbf20e376aa62ffd91c973493c41a7a52ddfd5a5db3ff9bc12f0d0fe9292
        target_directory: powershell
  - if: linux and aarch64
    then:
      - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/powershell-${{ version }}-linux-arm64.tar.gz
        sha256: a8d4e386dfafda385d0604045eed03ce6f3a843d45fc8f0b9588b836ca17cdb8
        target_directory: powershell
  - if: osx and arm64
    then:
      - url: https://github.com/PowerShell/PowerShell/releases/download/v${{ version }}/powershell-${{ version }}-osx-arm64.tar.gz
        sha256: 4b10e8a8e3dba067cf68c09bd92ee137ccac00b7c05ed31a0ae136309ef107b6
        target_directory: powershell


build:
  number: 0
  skip:
    - osx and x86_64  # Skip Intel macOS for now
  script:
    - if: win
      then: |
        xcopy powershell "%PREFIX%\powershell" /E /I /F /B /Y
        if %ERRORLEVEL% neq 0 exit 1
        echo F | xcopy %RECIPE_DIR%\pwsh.cmd %PREFIX%\Scripts\pwsh.cmd /F /Y
        if %ERRORLEVEL% neq 0 exit 1
    - if: unix
      then: |
        mkdir -p $PREFIX/powershell
        cp -r powershell/* $PREFIX/powershell/
        chmod +x $PREFIX/powershell/pwsh
        mkdir -p $PREFIX/bin
        cp $RECIPE_DIR/pwsh.sh $PREFIX/bin/pwsh
        chmod +x $PREFIX/bin/pwsh

requirements:
  run:
    - if: linux
      then:
        - icu


tests:
  - script:
      - if: win
        then:
          - where powershell
          - if not exist %PREFIX%\\powershell\\pwsh.exe exit 1
      - if: unix
        then:
          - which pwsh
          - test -x $PREFIX/powershell/pwsh
          - pwsh -Version

about:
  summary: PowerShell for every system!
  license: MIT
  license_file:
    - powershell/LICENSE.txt
    - powershell/ThirdPartyNotices.txt
    - powershell/assets/additionalAttributions.txt

  homepage: https://github.com/PowerShell/PowerShell

extra:
  recipe-maintainers:
    - chawyehsu
    - dhirschfeld
